name: codenic_exception_converter
description: A utility tool for converting Exception into Failure objects to make your code more portable and easier to maintain.
version: 5.2.4
repository: https://github.com/CodenicCoders/codenic_clean_arch/tree/main/packages/codenic_exception_converter
issue_tracker: https://github.com/CodenicCoders/codenic_clean_arch/issues
homepage: https://arch.codenic.dev
documentation: https://arch.codenic.dev/packages/codenic-exception-converter

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  equatable: ^2.0.7
  fpdart: ^1.1.1  

dev_dependencies:
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
