name: codenic_logger
description: A logger extension for providing structured and mutable log messages.
version: 4.1.3
repository: https://github.com/CodenicCoders/codenic_clean_arch/tree/main/packages/codenic_logger
issue_tracker: https://github.com/CodenicCoders/codenic_clean_arch/issues
homepage: https://arch.codenic.dev
documentation: https://arch.codenic.dev/packages/codenic-logger

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.8
  logger: ^2.6.2
  meta: ^1.17.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.28.0
  very_good_analysis: ^10.0.0
